POST https://ec2-54-237-118-91.compute-1.amazonaws.com:4000/login
Content-Type: application/json

{
    "username":"ak"
}

###
GET https://grovifyec2.nidhiworks.com:443



###

POST https://grovifyec2.nidhiworks.com:443/login
Content-Type: application/json

{
    "email":"sr@gmail.com",
    "password":"1234567890",
    "username":"sr"
}


###
GET https://grovifyec2.nidhiworks.com:443/getAllPlaylistAndSongs


###
POST https://grovifyec2.nidhiworks.com:443/insertPlaylist
Content-Type: application/json

{
    "email":"srinidhisasidharan@gmail.com",
    "playlist":"Selena",
    "songs":[]
}

###
POST https://grovifyec2.nidhiworks.com:443/insertPlaylist
Content-Type: application/json

{
    "email":"srinidhisasidharan@gmail.com",
    "playlist":"BTS",
    "songs":[
    {
        "title":"life goes on",
        "folder":"BTS",
        "duration":4,
        "artist":"BTS",
        "file":"life goes on.mp3"
    }]
}

###
POST  https://grovifyec2.nidhiworks.com:443/deleteFromPlaylist
Content-Type: application/json

{
    "email":"srinidhisasidharan@gmail.com",
    "playlist":"Taylor",
    "title":"life goes on"
}

###
DELETE   https://grovifyec2.nidhiworks.com:443/deletePlaylist
Content-Type: application/json

{
    "email":"srinidhisasidharan@gmail.com",
    "playlist":"Taylor"
}

###
POST https://grovifyec2.nidhiworks.com:443/userPlaylist
Content-Type: application/json

{
    "folder":"BTS"
}